Fix pre commit linting and testing
Upgrade to black 22.3.0 to fix `ImportError: cannot import name '_unicodefun' from 'click'`

Pin dependency on importlib-metadata to 4.12.0 to resolve `AttributeError: 'EntryPoints' object has no attribute 'get'`